# Battle Skill Training Config

skill_name: battle
rom_path: roms/pokemon_red.gb
init_state: saves/skill_states/battle_start.state

# Environment settings
env_kwargs:
  skill_max_steps: 200

# Vectorization
n_envs: 8
use_subproc: true

# Algorithm
algorithm: RecurrentPPO
policy: CnnLstmPolicy

# Hyperparameters
hyperparams:
  learning_rate: 0.0003
  n_steps: 128
  batch_size: 128
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

# Training
total_timesteps: 500000
checkpoint_freq: 25000
eval_freq: 10000
n_eval_episodes: 5

# Output
output_dir: models/skills/battle
