# Heal Skill Training Config

skill_name: heal
rom_path: roms/pokemon_red.gb
init_state: saves/skill_states/pokemon_center.state

# Environment settings
env_kwargs:
  skill_max_steps: 300

# Vectorization
n_envs: 4
use_subproc: false

# Algorithm
algorithm: RecurrentPPO
policy: CnnLstmPolicy

# Hyperparameters
hyperparams:
  learning_rate: 0.0003
  n_steps: 128
  batch_size: 64
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

# Training
total_timesteps: 200000
checkpoint_freq: 10000
eval_freq: 5000
n_eval_episodes: 5

# Output
output_dir: models/skills/heal
